site_name: MaadiX Documentación
site_description: Tutoriales y Gúias de uso
repo_url: https://github.com/MaadixNet/docs
edit_uri: edit/master/docs/
copyright: CC BY-SA 3.0 ES
pages:
    - Home: index.md
    - Panel&nbsp;de&nbsp;Control: panel-de-control.md
    - Usuarios: users.md
    - Dominios: dominios.md
    - DNS: dns.md
    - Email: email.md
    - VPN: vpn.md
    - Mysql: mysql.md
    - Etherpad: etherpad.md
    - Mailman: mail-man.md
    - Mailtrain: mailtrain.md
    - Libre&nbsp;Office&nbsp;Online: lool.md
    - OnlyOffice: onlyoffice.md
    - Crear&nbsp;Web: create-web.md
    - Wordpress: wordpress.md
    - Servidor&nbsp;TURN: coturn.md
    - Cambio&nbsp;de&nbsp;Nombre&nbsp;del&nbsp;Servidor: fqdn.md
theme: readthedocs
